### PR TITLE
Team page

### PR DESCRIPTION
**Pull request by ryandrew14**
This PR adds a team page with all of the current members on it. Let me know if I left any definites for the fall out. Also I punted on doing a hamburger menu for now, let me know if you think that's a bad choice. We probably have to have it at 3 menu items or more, but with 2 I'm thinking we can get away with this. I'll make an issue for that.

### CODE REVIEW

**Comment by ryandrew14** [comment]
Also, this closes #26.

**Comment by ryandrew14** [comment]
There also needs to be some way to contact us on this page, but I think that we should get this merged and make a follow up issue.

**Comment by dajinchu** [comment]
Need to add TEAM to the navigate section in the footer

**Comment by ryandrew14** [comment]
Good catch. Merging

**Pull request merged**
