### PR TITLE
new photos for karmen, ryan, tal

### PR DESCRIPTION
**Pull request by dajinchu**

### CODE REVIEW

**Comment by klu17** [comment]
Looks good to me. :)

**Comment by dajinchu** [comment]
> Looks gooD. Did you move Karmen on purpose? Currently it is ordered by semester joined, and within semester joined, ordered alphabetically. We can change that but we should change for everyone

Yeah I thought it looked weird with the inconsistent photo styles, so I put all of the different photos at the end of the list

**Comment by ryandrew14** [comment]
Got it, sounds good

**Comment by ryandrew14** [comment]
We good for this merge? @dajinchu

**Pull request merged**
